[package]
name = "sickle_math"
version = "0.4.0"
edition = "2021"
description = "Math dependencies for sickle_ui"
keywords = ["sickle_ui"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/UmbraLuminosa/sickle_ui"

[dependencies]
bevy_color = "0.15.0-rc.3"
bevy_reflect = "0.15.0-rc.3"
bevy_ui = "0.15.0-rc.3"
serde = { version = "1.0", features = ["derive"] }
