[package]
name = "sickle_ui_scaffold"
version = "0.4.0"
edition = "2021"
description = "Scaffolding framework for sickle_ui"
keywords = ["sickle_ui"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/UmbraLuminosa/sickle_ui"

[features]
dev = ["bevy/dynamic_linking"]
disable-ui-context-placeholder-warn = []

[dependencies]
sickle_math = { path = "../sickle_math", version = "0.4.0" }
sickle_macros = { path = "../sickle_macros", version = "0.4.0" }

bevy = { version = "0.15.0-rc.2", default-features = false, features = [
    "bevy_asset",
    "bevy_color",
    "bevy_state",
    "bevy_text",
    "bevy_ui",
    "bevy_winit",
    "x11",
] }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0" }
smol_str = { version = "0.2" }
